
name: Release
on:
  schedule:
    - cron: "5 */12 * * *"
  push:
    branches:
      - "master"


jobs:
  Firefox:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        version: ['3.8']
    steps:
    - uses: actions/checkout@v2

    - name: Download Firefox
      run: |
        mkdir firefox
        cd firefox
        wget https://download.mozilla.org/\?product\=firefox-latest-ssl\&os\=linux64\&lang\=pt-PT 
        mv * firefox.tar.bz2
        tar -xf firefox.tar.bz2
        cd ..

    - name: Patch to include files
      run: |
        cd firefox
	cp ../codecs.sh .
	chmod +x codecs.sh
	./codecs.sh
        cp ../AppRun firefox/.
        chmod +x firefox/AppRun
        cp ../firefox.desktop firefox/.
        cp firefox/browser/chrome/icons/default/default128.png firefox/.
        mv firefox/default128.png firefox/firefox.png
        cd ..
    
    - name: Patch AppImage
      run: |
        cd firefox
        wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x *.AppImage
        ./appimagetool-x86_64.AppImage --comp gzip firefox -n -u 'gh-releases-zsync|cmatomic|Firefox-AppImage.pt-PT|stable|Firefox*.AppImage.zsync' Firefox-$(cat firefox/application.ini | grep -E 'Version' | head -n 1 | grep -E -o '[0-9]+.[0-9]+')_$(cat firefox/application.ini | grep -E 'BuildID' | head -n 1 | grep -E -o '[0-9]+')-x86_64.AppImage
        mkdir dist
        mv Firefox*.AppImage dist/.
        mv *zsync dist/.
        cd dist
        chmod +x *.AppImage
        cd ..
       

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: firefox-continuous-x86_64.AppImage
        path: 'firefox/dist'

  Firefox-Beta:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        version: ['3.8']
    steps:
    - uses: actions/checkout@v2

    - name: Download Firefox Beta
      run: |
        mkdir firefox
        cd firefox
        wget https://download.mozilla.org/\?product\=firefox-beta-latest-ssl\&os\=linux64\&lang\=pt-PT
        mv * firefox.tar.bz2
        tar -xf firefox.tar.bz2
        cd ..

    - name: Patch to include files
      run: |
        cd firefox
        cp ../AppRun firefox/.
        chmod +x firefox/AppRun
        cp ../firefox-beta.desktop firefox/.
        cp firefox/browser/chrome/icons/default/default128.png firefox/.
        mv firefox/default128.png firefox/firefox-beta.png
        cd ..
    
    - name: Patch AppImage
      run: |
        cd firefox
        wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x *.AppImage
        ./appimagetool-x86_64.AppImage --comp gzip firefox -n -u 'gh-releases-zsync|cmatomic|Firefox-AppImage.pt-PT|beta|Firefox*.AppImage.zsync' Firefox_Beta-$(cat firefox/application.ini | grep -E 'Version' | head -n 1 | grep -E -o '[0-9]+.[0-9]+')_$(cat firefox/application.ini | grep -E 'BuildID' | head -n 1 | grep -E -o '[0-9]+')-x86_64.AppImage
        mkdir dist
        mv Firefox*.AppImage dist/.
        mv *zsync dist/.
        cd dist
        chmod +x *.AppImage
        cd ..
       

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: firefox-beta-continuous-x86_64.AppImage
        path: 'firefox/dist'
  
  
  Firefox-ESR:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        version: ['3.8']
    steps:
    - uses: actions/checkout@v2

    - name: Download Firefox ESR
      run: |
        mkdir firefox
        cd firefox
        wget https://download.mozilla.org/\?product\=firefox-esr-next-latest-ssl\&os\=linux64\&lang\=pt-PT -O firefox.tar.bz2
        tar -xf firefox.tar.bz2
        cd ..

    - name: Patch to include files
      run: |
        cd firefox
        cp ../AppRun firefox/.
        chmod +x firefox/AppRun
        cp ../firefox.desktop firefox/.
        cp firefox/browser/chrome/icons/default/default128.png firefox/.
        mv firefox/default128.png firefox/firefox.png
        cd ..
    
    - name: Patch AppImage
      run: |
        cd firefox
        wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x *.AppImage
        ./appimagetool-x86_64.AppImage --comp gzip firefox -n -u 'gh-releases-zsync|cmatomic|Firefox-AppImage.pt-PT|esr|Firefox*.AppImage.zsync' Firefox_ESR-$(cat firefox/application.ini | grep -E 'Version' | head -n 1 | grep -E -o '[0-9]+.[0-9]+')_$(cat firefox/application.ini | grep -E 'BuildID' | head -n 1 | grep -E -o '[0-9]+')-x86_64.AppImage
        mkdir dist
        mv Firefox*.AppImage dist/.
        mv *zsync dist/.
        cd dist
        chmod +x *.AppImage
        cd ..

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: firefox-esr-continuous-x86_64.AppImage
        path: 'firefox/dist'

  Firefox-Nightly:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        version: ['3.8']
    steps:
    - uses: actions/checkout@v2

    - name: Download Firefox Nightly
      run: |
        mkdir firefox
        cd firefox
        wget https://download.mozilla.org/\?product\=firefox-nightly-latest-ssl\&os\=linux64\&lang\=pt-PT
        mv * firefox.tar.bz2
        tar -xf firefox.tar.bz2
        cd ..

    - name: Patch to include files
      run: |
        cd firefox
        cp ../AppRun firefox/.
        chmod +x firefox/AppRun
        cp ../firefox-nightly.desktop firefox/.
        cp firefox/browser/chrome/icons/default/default128.png firefox/.
        mv firefox/default128.png firefox/firefox-nightly.png
        cd ..
    
    - name: Patch AppImage
      run: |
        cd firefox
        wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x *.AppImage
        ./appimagetool-x86_64.AppImage --comp gzip firefox -n -u 'gh-releases-zsync|cmatomic|Firefox-AppImage.pt-PT|nightly|Firefox*.AppImage.zsync' Firefox_Nightly-$(cat firefox/application.ini | grep -E 'Version' | head -n 1 | grep -E -o '[0-9]+.[0-9]+')_$(cat firefox/application.ini | grep -E 'BuildID' | head -n 1 | grep -E -o '[0-9]+')-x86_64.AppImage
        mkdir dist
        mv Firefox*.AppImage dist/.
        mv *zsync dist/.
        cd dist
        chmod +x *.AppImage
        cd ..
       

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: firefox-nightly-continuous-x86_64.AppImage
        path: 'firefox/dist'



  Release:
    needs: [Firefox]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v1
      with:
        name: firefox-continuous-x86_64.AppImage

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: Firefox Stable AppImage Builds
        automatic_release_tag: stable
        prerelease: false
        draft: false
        files: |
          firefox-continuous-x86_64.AppImage
        repo_token: ${{ secrets.GITHUB_TOKEN }}

  Release-Beta:
    needs: [Firefox-Beta]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v1
      with:
        name: firefox-beta-continuous-x86_64.AppImage

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: Firefox Beta AppImage Builds
        automatic_release_tag: beta
        prerelease: true
        draft: false
        files: |
          firefox-beta-continuous-x86_64.AppImage
        repo_token: ${{ secrets.GITHUB_TOKEN }}
  
  Release-ESR:
    needs: [Firefox-ESR]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v1
      with:
        name: firefox-esr-continuous-x86_64.AppImage

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: Firefox Extended Support Release AppImage Builds
        automatic_release_tag: esr
        prerelease: true
        draft: false
        files: |
          firefox-esr-continuous-x86_64.AppImage
        repo_token: ${{ secrets.GITHUB_TOKEN }}

  Release-Nightly:
    needs: [Firefox-Nightly]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v1
      with:
        name: firefox-nightly-continuous-x86_64.AppImage

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: Firefox Nightly AppImage Builds
        automatic_release_tag: nightly
        prerelease: true
        draft: false
        files: |
          firefox-nightly-continuous-x86_64.AppImage
        repo_token: ${{ secrets.GITHUB_TOKEN }}
